
import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ximena
 */
public class taller extends javax.swing.JFrame {

    /**
     * Creates new form taller
     */
    public taller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setText("punto1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("punto2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("punto3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("punto4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("punto5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("punto6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("punto7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("punto8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton8))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(26, 26, 26))
        );

        jLabel1.setText("TALLER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        int valora;
        int valorb;
        int resultadoSuma, resultadoResta;
        double residuo;
        
        Scanner entrada= new Scanner (System.in);
        
        System.out.print("escribe el valor a:");
         valora= Integer.parseInt(entrada.next());
         
         System.out.print("escribe el valor b:");
         valorb= Integer.parseInt(entrada.next());
         
        resultadoSuma= valora+valorb;
        System.out.print(" resultado de la suma es:"+resultadoSuma);
        
        resultadoResta= valora-valorb;
        System.out.print(" resultado de la resta es:"+resultadoResta);
        
        residuo=(valora%valorb);
        System.out.print(" resultado del residuo es:"+residuo);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         String animal;
        Scanner sc = new Scanner(System.in);
        System.out.println("Ingrese el nombre de un ser vivo");
        animal = sc.nextLine();
        if ("perro".equalsIgnoreCase(animal)||"gato".equalsIgnoreCase(animal)||"vaca".equalsIgnoreCase(animal)||"burro".equalsIgnoreCase(animal)||"tortuga".equalsIgnoreCase(animal)) {
            System.out.println("Pertenece al reino animalia.");
        }else{
            if ("algas".equalsIgnoreCase(animal)||"musgo".equalsIgnoreCase(animal)||"helechos".equalsIgnoreCase(animal)||"orquideas".equalsIgnoreCase(animal)||"flores".equalsIgnoreCase(animal)) {
                System.out.println("Pertenece al reino Plantae.");
            }else{
                if ("champiñon".equalsIgnoreCase(animal)||"matamoscas".equalsIgnoreCase(animal)||"penicillium".equalsIgnoreCase(animal)||"hongo de pino".equalsIgnoreCase(animal)||"levadura".equalsIgnoreCase(animal)) {
                    System.out.println("Pertenece al reino Fungi.");
                }else{
                    if ("protozoo".equalsIgnoreCase(animal)||"paramecio".equalsIgnoreCase(animal)||"volvox".equalsIgnoreCase(animal)||"laurencia".equalsIgnoreCase(animal)||"amoeba".equalsIgnoreCase(animal)) {
                        System.out.println("Pertenece al reino Protista.");
                    } else {
                        if ("salmonella".equalsIgnoreCase(animal)||"coli".equalsIgnoreCase(animal)||"subtilit".equalsIgnoreCase(animal)||"tetani".equalsIgnoreCase(animal)||"aerogenes".equalsIgnoreCase(animal)) {
                            System.out.println("Pertenece al reino Bacteria.");
                        } else {
                            if ("halofilos".equalsIgnoreCase(animal)||"termoacidofilos".equalsIgnoreCase(animal)||"metanogenos".equalsIgnoreCase(animal)||"odinarchaeota".equalsIgnoreCase(animal)||"thorarchaeota".equalsIgnoreCase(animal)) {
                                System.out.println("Pertenece al reino Archea.");
                            } else {
                                System.out.println("Ingrese un ser vivo que esté regustrado en el programa.");
                            }
                        }
                    }
                }
            }
        }
    
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       int num;
        
        num= Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese el numero del 1 al 7"));
        
        switch (num)
        {
            case 1: JOptionPane.showInputDialog(null, " DO ");
                   break;
                   
            case 2: JOptionPane.showInputDialog(null, " RE ");
                   break;
                   
            case 3: JOptionPane.showInputDialog(null, " MI ");
                   break;
                   
            case 4: JOptionPane.showInputDialog(null, " FA ");
                   break;
                   
            case 5: JOptionPane.showInputDialog(null, " SOL ");
                   break;
                   
            case 6: JOptionPane.showInputDialog(null, " LA ");
                   break;
                   
            case 7: JOptionPane.showInputDialog(null, " SI ");
                   break;
                   
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    int a;
     a= Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese el numero para contar"));
     
     for (int i=0; i <=a; i++){
         JOptionPane.showInputDialog(null, i);
     }

         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    int b;
        b= Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese el numero"));
        
        for(int i=0; i<=b; i+=3) {
            
            JOptionPane.showInputDialog(null, " la serie de numeros es "+i);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

     int c;
     c= Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese el numero"));
     
      if (c%2==0){
          
          JOptionPane.showInputDialog(null, " el numero es par ");
      } else {
          
          JOptionPane.showInputDialog(null, " el numero es impar ");
      }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
         int a, nb, nc,acumulador,contador;
        
        a = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el numero para la serie "));
        nb=1;
        nc=0;
        acumulador=0;
        contador=1;
        
        while (contador<=a) {      
            JOptionPane.showMessageDialog(null,+ acumulador);
            acumulador= nb + nc;
            nb = nc;
            nc=acumulador;
            contador++;
  
        
    }
             
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

   Scanner teclado= new Scanner(System.in);
	int numero1=0;
	int numero2=0;
	int intentos=1;
	int maximo=3;
			
	while((numero1!=5)||(numero2!=9)&& (intentos<maximo)){
					
	    System.out.print("introduzca numero1: ");
	    numero1=teclado.nextInt();
	    System.out.print("Introduzca numero2:");
	    numero2=teclado.nextInt();
					
		if(intentos==3){
		    System.out.println("acceso denegado.");
		    intentos=intentos-maximo;
	}
         intentos++;
				
				
	}
		
	System.out.println("numero1 y numero2, correctos.");



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new taller().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
